### ISSUE TITLE
Bash and The One True Path

### ISSUE THREAD

**Issue by rsleiberin** [learn-co-curriculum/phase-0-bash-navigation#4]
### Canvas Link

https://learning.flatironschool.com/courses/5166/pages/bash-navigation?module_item_id=341578

### Concern

The resource "Bash and The One True Path" at the end of the listed page is invalid and reads:

URL: http://blog.seldomatt.com/blog/2012/10/08/bash-and-the-one-true-path/

目标站当前地址无法打开!

Google Translate:

"The current address of the target station cannot be opened!"

### Suggested Changes

Remove resource list, update old resource to new url, or update to a new resource with similar content.

**Comment by graciemcguire** [comment]
Thanks for submitting this issue @rsleiberin ! This link is no longer in this lesson. 
Please note that the change will not be reflected in your Canvas, but is in the Github repository, and will be in Canvas for future students. 
Happy coding!
